In [ ]:
'''
Practical No.3: Write a NumPy program to implement following operation
Name:panera ghanshyam
Enroll no:216270307072
'''

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [ ]:
'''
Practical No.3: Write a NumPy program to implement following operation

to split an array of 14 elements into 3 arrays, each with 2, 4, and 8 elements in the original order

Name:panera ghanshyam
Enroll no:216270307072
'''
a=np.arange(1,15)

print(a,"\n")

a1,a2,a3=np.split(a,(2,6))
print(a1,"\n")
print(a2,"\n")
print(a3,"\n")

In [ ]:
'''
Practical No.3: Write a NumPy program to implement following operation

to stack arrays horizontally (column wise)\

Name:panera ghanshyam
Enroll no:216270307072
'''
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[7,8],[9,10]])

a3=np.hstack((a1,a2))
print(a1,"\n")
print(a2,"\n")
print(a3,"\n")